#!/bin/tcsh -fx

set apkDir = /Users/dulinglai/Documents/Study/ResearchProjects/LocationFreq/APK_transformation/testApks
cd $apkDir/decompiled/instrumented/
set androidTool = /Users/dulinglai/Library/Android/sdk/build-tools/27.0.3
set apktoolDir = /Users/dulinglai/Documents/Study/ResearchProjects/Tools/
set tmpDir = /Users/dulinglai/Documents/Study/ResearchProjects/LocationFreq/APK_transformation/testApks/decompiled/instrumented/tmp

echo "Replacing AndroidManifest.xml"
java -jar $apktoolDir/apktool.jar b $tmpDir -o tmp.apk
unzip tmp.apk AndroidManifest.xml
zip -r $1_unaligned.apk AndroidManifest.xml

rm -f tmp.apk
rm -f AndroidManifest.xml

echo "Replacing classes.dex file"
if (-f classes2.dex) then
  $androidTool/aapt add $apkDir/decompiled/instrumented/$1_unaligned.apk classes.dex
  $androidTool/aapt add $apkDir/decompiled/instrumented/$1_unaligned.apk classes2.dex
  rm classes.dex
  rm classes2.dex
else
  $androidTool/aapt add $apkDir/decompiled/instrumented/$1_unaligned.apk classes.dex
  rm classes.dex
endif